name: Storyblok published

on:
  # Allows workflow to be manually run in Github UI
  workflow_dispatch:
  # Allows workflow to be called via HTTP calls to GitHub (with correct auth, etc)
  repository_dispatch:
    types: [storyblok-published]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download stories from Storyblok and add changes to git
        env:
          STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
        run: |
          declare -a stories=("footer","home","navigation")
          for story in "${stories[@]}"
          do
            curl "https://api.storyblok.com/v2/cdn/stories/$story?token=$STORYBLOK_TOKEN" \
              -L -X GET \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              | jq > storyblok/data/$story.json
            git add storyblok/data/$story.json
          done
      - name: Commit Changes and Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: auto/storyblok-published-changes
          commit-message: Latest changes from Storyblok
          committer: GitHub Action Bot - Storybook Published <noreply@github.com>
          author: GitHub Action Bot - Storybook Published <noreply@github.com>
          title: "[Storyblok] Latest published changes"
          body: |
            Automatically created by Storyblok-Published Github action
          labels: |
            automated-pr
            storyblok-pr
