name: Storyblok published

on:
  workflow_dispatch:
  repository_dispatch:
    types: [storyblok-published]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Configure git
      #   run: |
      #     git config user.name "GitHub Action Bot - Storybook Published"
      #     git config user.email "<>"
      # - name: Create fresh auto/storyblok-published-changes branch from main 
        run: |
          git checkout main
          git branch --force auto/storyblok-published-changes
          git checkout auto/storyblok-published-changes
      - name: Download stories from Storyblok and add changes to git
        env:
          STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
        run: |
          declare -a stories=("home")
          for story in "${stories[@]}"
          do
            curl "https://api.storyblok.com/v2/cdn/stories/$story?token=$STORYBLOK_TOKEN" \
              -X GET \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              > storyblok_data/$story.json
            git add storyblok_data/$story.json
          done
      # - name: Commit Storyblok changes to branch
      #   run: | 
      #     git commit -m "Latest changes from Storyblok - automatically pulled at $(date)"
      # - name: Force push auto/storyblok-published-changes
      #   run: |
      #     git push --force origin auto/storyblok-published-changes
      # - name: Create Pull Request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh pr create -B main -H auto/storyblok-published-changes \
      #       --title 'Storyblok - Latest published changes' \
      #       --body 'Automatically created by Storyblok-Published Github action'
      - name: Commit Changes and Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Latest changes from Storyblok
          committer: GitHub Action Bot - Storybook Published <>
          author: GitHub Action Bot - Storybook Published <>
          branch: auto/storyblok-published-changes
          title: '[Storyblok] Latest published changes'
          body: |
            Automatically created by Storyblok-Published Github action
          # labels: |
          #   report
          #   automated pr