name: Storyblok published

on:
  repository_dispatch:
    types: [storyblok-published]

permissions:
  contents: write

jobs:
  create-or-update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create fresh auto/storyblok-published-changes branch from main 
        run: |
          git checkout main
          git branch --force auto/storyblok-published-changes
          git checkout auto/storyblok-published-changes
      - name: Download stories from Storyblok
        env:
          STORYBLOK_TOKEN: ${{ secrets.STORYBLOK_TOKEN }}
        run: |
          declare -a stories=("home")
          for story in "${stories[@]}"
          do
            curl "https://api.storyblok.com/v2/cdn/stories/$story?token=$STORYBLOK_TOKEN" \
            -X GET \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            > storyblok_data/$story
          done
      - name: Commit Storyblok changes to branch
        run: | 
          git commit -am 'Latest changes from Storyblok - automatically pulled at $(date)'
      - name: Force push auto/storyblok-published-changes
          git push --force origin auto/storyblok-published-changes
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B main -H auto/storyblok-published-changes /
            --title 'Storyblok - Latest published changes' /
            --body 'Automatically created by Storyblok-Published Github action'